name: CI/CD Workflow

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Latest Code from GitHub to Server
        run: |
          rsync -avh --exclude='.git' ./ /var/www/html/backend-yoexstaking

      - name: Install Dependencies
        run: |
          rm -rf backend-yoexstaking/server/db/database.js
          cp /var/www/html/database.js backend-yoexstaking/server/db/
          cd /var/www/html/backend-yoexstaking
          npm install

      - name: Restart Application with PM2
        run: |
          pm2 restart 0

